name: medd
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
dependencies:
  - _openmp_mutex=4.5
  - asttokens=3.0.0
  - blas=1.0
  - brotli-python=1.1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - cccl=3.0.1
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.2.3
  - cpython=3.11.14
  - cuda-cccl=13.0.85
  - cuda-cccl_linux-64=13.0.85
  - cuda-cccl_win-64=13.0.85
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=12.4.127
  - cuda-cupti=12.4.127
  - cuda-driver-dev=13.0.96
  - cuda-driver-dev_linux-64=13.0.96
  - cuda-libraries=12.4.1
  - cuda-libraries-dev=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvrtc-dev=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=13.0.85
  - cuda-opencl-dev=13.0.85
  - cuda-profiler-api=13.0.85
  - cuda-runtime=12.4.1
  - cuda-version=13.0
  - debugpy=1.8.17
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - filelock=3.17.0
  - freetype=2.13.3
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.7
  - importlib-metadata=8.7.0
  - ipykernel=7.0.1
  - ipython=9.6.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9f
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.44
  - lerc=3.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=12.4.5.8
  - libcublas-dev=12.4.5.8
  - libcufft=11.2.1.3
  - libcufft-dev=11.2.1.3
  - libcufile=1.15.0.42
  - libcufile-dev=1.15.0.42
  - libcurand=10.4.0.35
  - libcurand-dev=10.4.0.35
  - libcusolver=11.6.1.9
  - libcusolver-dev=11.6.1.9
  - libcusparse=12.3.1.170
  - libcusparse-dev=12.3.1.170
  - libdeflate=1.17
  - libedit=3.1.20250104
  - libexpat=2.7.1
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.2.0
  - libgfortran-ng=15.2.0
  - libgfortran5=15.2.0
  - libhwloc=2.9.0
  - libiconv=1.18
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - liblzma-devel=5.6.4
  - libnl=3.11.0
  - libnpp=12.2.5.30
  - libnpp-dev=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=13.0.85
  - libnvfatbin-dev=13.0.85
  - libnvjitlink=12.4.127
  - libnvjitlink-dev=12.4.127
  - libnvjpeg=12.3.1.117
  - libnvjpeg-dev=12.3.1.117
  - libogg=1.3.5
  - libopus=1.5.2
  - libpng=1.6.39
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsqlite=3.50.2
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.5.1
  - libuuid=1.41.5
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxml2=2.13.7
  - libzlib=1.3.1
  - llvm-openmp=21.1.4
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - numpy=2.3.4
  - ocl-icd=2.3.3
  - opencl-headers=2025.06.13
  - openjpeg=2.5.2
  - openssl=3.5.4
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.2
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.23
  - pygments=2.19.2
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python_abi=3.11
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pywin32=311
  - pyyaml=6.0.2
  - pyzmq=27.1.0
  - rdma-core=58.0
  - readline=8.3
  - requests=2.32.5
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - sympy=1.14.0
  - tbb=2021.8.0
  - tk=8.6.15
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - urllib3=2.5.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - xz-gpl-tools=5.6.4
  - xz-tools=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - accelerate==1.11.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.1
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anyio==4.11.0
      - attrs==25.4.0
      - av==16.0.1
      - bitsandbytes==0.48.1
      - coloredlogs==15.0.1
      - coverage==7.11.0
      - ctranslate2==4.6.0
      - cut-cross-entropy==25.1.1
      - datasets==4.2.0
      - diffusers==0.35.2
      - dill==0.4.0
      - diskcache==5.6.3
      - docstring-parser==0.17.0
      - faster-whisper==1.2.0
      - ffmpeg==1.4
      - flake8==7.3.0
      - flatbuffers==25.9.23
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - h11==0.16.0
      - hf-transfer==0.1.9
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - humanfriendly==10.0
      - hyperpyyaml==1.2.2
      - ipywidgets==8.1.7
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyterlab-widgets==3.0.15
      - llama-cpp-python==0.3.16
      - markdown-it-py==4.0.0
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mistral-common==1.8.5
      - mock==5.2.0
      - msgspec==0.19.0
      - multidict==6.7.0
      - multiprocess==0.70.16
      - nose==1.3.7
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - onnxruntime==1.23.2
      - pandas==2.3.3
      - peft==0.17.1
      - pip-conflict-checker==0.6.0
      - pipdeptree==2.29.0
      - propcache==0.4.1
      - protobuf==6.33.0
      - pyarrow==21.0.0
      - pycodestyle==2.14.0
      - pycountry==24.6.1
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pydantic-extra-types==2.10.6
      - pyflakes==3.4.0
      - pyreadline3==3.5.4
      - pysoundfile==0.9.0.post1
      - pytz==2025.2
      - referencing==0.37.0
      - regex==2025.10.23
      - rich==14.2.0
      - rpds-py==0.27.1
      - ruamel-yaml==0.18.15
      - ruamel-yaml-clib==0.2.14
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.2
      - sentencepiece==0.2.1
      - shtab==1.7.2
      - sniffio==1.3.1
      - speechbrain==1.0.3
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - torch==2.8.0
      - torchao==0.13.0
      - torchaudio==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - transformers==4.56.2
      - triton==3.4.0
      - trl==0.23.0
      - typeguard==4.4.4
      - typing-inspection==0.4.2
      - tyro==0.9.35
      - tzdata==2025.2
      - unsloth==2025.10.7
      - unsloth-zoo==2025.10.8
      - widgetsnbextension==4.0.14
      - xformers==0.0.32.post2
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /home/devcontainers/miniconda3/envs/medd
